name: Haskell - lint

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - trunk

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: haskell-actions/run-ormolu@v14
        with:
          pattern: |
            wasm-calc/**/*.hs
            wasm-calc2/**/*.hs
            wasm-calc3/**/*.hs
            wasm-calc4/**/*.hs
            wasm-calc5/**/*.hs

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: "Set up HLint"
        uses: rwe/actions-hlint-setup@v1
        with:
          version: "3.5"

      - name: "Run HLint"
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["wasm-calc/", "wasm-calc2/", "wasm-calc3/", "wasm-calc4/", "wasm-calc5/"]'
          fail-on: warning

