name: WASM calculator - build

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: wasm-calc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build everything
        run: nix flake check -j auto

  build-allocator:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      matrix:
        version: [9, 10, 11]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: wasm-calc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and diff allocator
        run: nix develop --command make build-malloc version=${{ matrix.version }}

