name: WASM calculator - build

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Cache cabal global package db
        id: cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-2-wasm-calc-cabal-global-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-2-wasm-calc-cabal-global-${{ matrix.plan.ghc }}

      - name: Cache .cabal-work
        uses: actions/cache@v3
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-2-wasm-calc-cabal-work-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-2-wasm-calc-cabal-work-${{ matrix.plan.ghc }}

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix develop --command true
        run: |
          nix develop --print-build-logs --command true

      - name: Build the universe
        run: nix develop --command make build

      - name: Test wasm-calc
        run: nix develop --command make test-wasm-calc

      - name: Test wasm-calc2
        run: nix develop --command make test-wasm-calc2

      - name: Test wasm-calc3
        run: nix develop --command make test-wasm-calc3

      - name: Test wasm-calc4
        run: nix develop --command make test-wasm-calc4

      - name: Test wasm-calc5
        run: nix develop --command make test-wasm-calc5

      - name: Test wasm-calc6
        run: nix develop --command make test-wasm-calc6

      - name: Test wasm-calc7
        run: nix develop --command make test-wasm-calc7

      - name: Test wasm-calc8
        run: nix develop --command make test-wasm-calc8

      - name: Test wasm-calc9
        run: nix develop --command make test-wasm-calc9
